{% set name = "django-keyedcache3" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-keyedcache3-{{ version }}.tar.gz
  sha256: aa18aa14fb010ab017be26c97e30b477d63a8b75f22e1a3c3ec27ae2e6d5363c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=1.8

test:
  commands:
    - python -c "import importlib.util; assert importlib.util.find_spec('keyedcache')"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kunaldeo/django-keyedcache3
  summary: keyedcache
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mxr-conda
    - rxm7706
